### ISSUE TITLE
"genie learn interface" raises exception on a minimally configured 2960S

### ISSUE THREAD

**Issue by jesse-mcgraw** [CiscoTestAutomation/genielibs#11]
Command:
genie learn interface --testbed-file testbed.yaml --output output/

[show_run.txt](https://github.com/CiscoTestAutomation/genielibs/files/3277518/show_run.txt)
[show_ver.txt](https://github.com/CiscoTestAutomation/genielibs/files/3277519/show_ver.txt)
[pip_freeze.txt](https://github.com/CiscoTestAutomation/genielibs/files/3277528/pip_freeze.txt)
[interface_ios_lab_2960_s_exception..txt](https://github.com/CiscoTestAutomation/genielibs/files/3277541/interface_ios_lab_2960_s_exception.txt)

**Comment by karmoham** [comment]
Hi Jesse,

Thanks for reporting the issue, we will look into it and get back to you.

Thanks,
Karim

**Comment by jesse-mcgraw** [comment]
Using 19.5.2b2 has resolved this issue

**Comment by karmoham** [comment]
Hi Jesse,

Glad to hear that!

Thanks,
Karim
