### ISSUE TITLE
Model browser, object model docs 404 not found

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genielibs#13]
When clicking on any of the object models in the Genie models browser, I get a 404 not found.

As an example...

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: media/genie-feature-browser/_models/hsrp.pdf
RequestId: DEF92801D6AF2108
HostId: 90QyLnucCBTFlLYqVaaDn+Rl4rqVwd9RelXGrK5knda8K5qpAFHYEpsCvxq1K3adexdSpGKduQ0=
```

**Comment by siming85** [comment]
!

We just moved the documentation to a new repo, looks like something was missed. will fix ASAP!

**Comment by siming85** [comment]
pushed new doc fixes.
this has been resolved.

our apologies for the inconvenience!
