### ISSUE TITLE
Missing API parameters in documentation

### ISSUE THREAD

**Issue by joabda** [CiscoTestAutomation/genielibs#135]
https://github.com/CiscoTestAutomation/genielibs/blob/2555acd0c1f0cfc65f4c07f162cdb958a5e1fab8/pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/dhcp/configure.py#L11-L25

In the [pubhub documentation for create_dhcp_pool](https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/apis/create_dhcp_pool) the lease parameters are missing. 

I proposed to replace the current function's documentation with the following:
```python
def create_dhcp_pool(
    device, pool_name, network, mask, router_id,lease_days,lease_hrs,lease_mins
):
    """ Create DHCP pool
        Args:
            device ('obj'): device to use
            pool_name ('str'): name of the pool to be created
            network ('str'): IP of the network pool
            mask ('str'): Subnet mask of the network pool
            router_id ('str'): Default router ID
            lease_days ('str'): Number of days for the lease
            lease_hrs ('str'): Number of hours for the lease
            lease_mins ('str'): Number of minutes for the lease
        Returns:
            None
        Raises:
            SubCommandFailure: Failed creating dhcp pool
    """
```

I assume the pubhub documentation is generated from the python function documentation.

**Comment by sowmyadn010501** [comment]
Hello joabda,
I will be looking in to your issue. Kindly give me some time to analyze the issue.

**Comment by SohanTirpude** [comment]
@joabda raised the PR #136 for this issue.

**Comment by sowmyadn010501** [comment]
As your PR has been merged, the changes will reflect next new version. Hence closing this ticket
In the future after the changes has been reflected, if you still face the issue we can reopen this ticket.
