### ISSUE TITLE
libs.robot.GenieRobot System Profiling: SchemaMissingKeyError

### ISSUE THREAD

**Issue by marehler** [CiscoTestAutomation/genielibs#147]
When using genie.libs.robot.GenieRobot with NX-OS, the 'Profile the system for "vxlan" on devices <...>' Robot keyword fails (output anonymized):

```
2023-11-27 15:44:08,482: %UNICON-INFO: +++ ***Hostname*** with via 'cli': executing command 'show bgp l2vpn evpn summary' +++

show bgp l2vpn evpn summary
BGP summary information for VRF default, address family L2VPN EVPN
BGP router identifier ***IP Adress***, local AS number ***AS***
BGP table version is 1572, L2VPN EVPN config peers 2, capable peers 2
131 network entries and 241 paths using 35564 bytes of memory
BGP attribute entries [94/16168], BGP AS path entries [4/36]
BGP community entries [0/0], BGP clusterlist entries [8/32]
Neighbor V AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down State/PfxRcd
***IP Adress***, ***AS*** 78400 77855 1572 0 0 7w5d 80
***IP Adress***, 4 ***AS***  78426 77858 1572 0 0 7w5d 80

15:44:08.692 FAIL SchemaMissingKeyError: Missing keys: [['instance', 'default', 'vrf', 'default', 'address_family', 'l2vpn evpn', 'neighbor']]
```

The same keyword works for other features or show commands. Not sure if this is a /genielibs or /genieparser issue.

**Comment by marehler** [comment]
Hi @kameswararaot,
Sure, thanks for picking it up.

**Comment by kameswararaot** [comment]
Hi marehler,

I have one doubt at "Neighbour" is there any "IP Add" or "***IP Address***" and "AS" is there any "AS number" or "***AS***". 
Could you please address the current changes, otherwise kindly share the exact device output.

**Comment by marehler** [comment]
The output is anonymized to hide confidential data. In the actual output there are of course actual IP addresses / AS numbers instead of ***IP Adress*** / ***AS***.

**Comment by kameswararaot** [comment]
Hi marehler,

Thanks for the update. I will check it an d let you know the status.

**Comment by kameswararaot** [comment]
Hi marehler,

```
show bgp l2vpn evpn summary
BGP summary information for VRF default, address family L2VPN EVPN
BGP router identifier 192.168.1.0, local AS number 100
BGP table version is 1572, L2VPN EVPN config peers 2, capable peers 2
131 network entries and 241 paths using 35564 bytes of memory
BGP attribute entries [94/16168], BGP AS path entries [4/36]
BGP community entries [0/0], BGP clusterlist entries [8/32]
Neighbor V AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down State/PfxRcd
192.168.1.1 4 100 78400 77855 1572 0 0 7w5d 80
192.168.1.2 4 200  78426 77858 1572 0 0 7w5d 80
```

I have given the dummpy IP and dummy AS number, and I parsed the output without any change in code.
I am getting the output. Please find the output also.

```
{
    "instance": {
        "default": {
            "vrf": {
                "default": {
                    "vrf_name_out": "default",
                    "address_family": {
                        "l2vpn evpn": {
                            "tableversion": 1572,
                            "configuredpeers": 2,
                            "capablepeers": 2,
                            "totalnetworks": 131,
                            "totalpaths": 241,
                            "memoryused": 35564,
                            "dampening": "disabled",
                            "numberattrs": 94,
                            "bytesattrs": 16168,
                            "numberpaths": 4,
                            "bytespaths": 36,
                            "numbercommunities": 0,
                            "bytescommunities": 0,
                            "numberclusterlist": 8,
                            "bytesclusterlist": 32,
                            "neighbor": {
                                "192.168.1.1": {
                                    "neighbor": "192.168.1.1",
                                    "remoteas": 100,
                                    "version": 4,
                                    "msgrecvd": 78400,
                                    "msgsent": 77855,
                                    "neighbortableversion": 1572,
                                    "inq": 0,
                                    "outq": 0,
                                    "time": "7w5d",
                                    "prefixreceived": 80,
                                    "state": "established"
                                },
                                "192.168.1.2": {
                                    "neighbor": "192.168.1.2",
                                    "remoteas": 200,
                                    "version": 4,
                                    "msgrecvd": 78426,
                                    "msgsent": 77858,
                                    "neighbortableversion": 1572,
                                    "inq": 0,
                                    "outq": 0,
                                    "time": "7w5d",
                                    "prefixreceived": 80,
                                    "state": "established"
                                }
                            }
                        }
                    },
                    "vrf_router_id": "192.168.1.0",
                    "vrf_local_as": 100
                }
            }
        }
    }
}

```

Please check it and once and let me know the status.

**Comment by marehler** [comment]
Hi @kameswararaot,

I had opened this issue on behalf of one of my customers. Let me involve him directly for feedback and further clarification. One hint, in the original output there are line breaks due to 4-byte AS lengths. Don't know if that potentially could cause an issue.

**Comment by marehler** [comment]
Dear @spasekovachev,

Could you please review and comment, in particular how to reproduce the issue?

**Comment by spasekovachev** [comment]
Hi @kameswararaot,
hier again the output which has't be parsed.
`2023-12-12 09:14:35,848: %UNICON-INFO: +++ ***Hostname*** with via 'cli': executing command 'show bgp l2vpn evpn summary' +++
show bgp l2vpn evpn summary
BGP summary information for VRF default, address family L2VPN EVPN
BGP router identifier ***IP***, local AS number ***4B ASN***
BGP table version is 5549, L2VPN EVPN config peers 2, capable peers 2
293 network entries and 442 paths using 72332 bytes of memory
BGP attribute entries [110/18920], BGP AS path entries [5/54]
BGP community entries [0/0], BGP clusterlist entries [8/32]

Neighbor        V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
***IP***   4 ***4B ASN***
                         121842  120925     5549    0    0    11w6d 142       
***IP***   4 ***4B ASN***
                         118316  117369     5549    0    0     3w4d 142`
    

also the steps to reproduce it
`genie shell --testbed-file testbed.yaml
testbed.devices
nx = testbed.devices['***Hostname***']
nx.connect()
vxlan = nx.learn('vxlan')`

**Comment by kameswararaot** [comment]
Hi @spasekovachev,
 
Please share the output properly. If any confidential information link IP and AS number. Please give some dummy ip and dummy AS number. 

example:- 
show bgp l2vpn evpn summary
BGP summary information for VRF default, address family L2VPN EVPN
BGP router identifier IP, local AS number 4B ASN  <<<<<<  ( Here please add dummy IP and dummy AS number)
BGP table version is 5549, L2VPN EVPN config peers 2, capable peers 2
293 network entries and 442 paths using 72332 bytes of memory
BGP attribute entries [110/18920], BGP AS path entries [5/54]
BGP community entries [0/0], BGP clusterlist entries [8/32]

Neighbor V AS MsgRcvd MsgSent TblVer InQ OutQ Up/Down State/PfxRcd
IP 4 4B ASN  <<<<<<  ( Here please add dummy IP and dummy AS number)
121842 120925 5549 0 0 11w6d 142  <<<<<<<(This line should be in new line? If not please let me know as per below line)
**IP 4 4B ASN 121842 120925 5549 0 0 11w6d 142** 


Please add the dummy details like this below.
**BGP router identifier 192.168.1.1, local AS number 100**  <<<<<< ( add the details like this with dummy details)
**192.168.1.1 4 100  118316 117369 5549 0 0 3w4d 142**   <<<<<< ( add the details like this with dummy details)

Without proper details we are unable to do changes.

**Comment by spasekovachev** [comment]
Hi @kameswararaot,
please find the attached output 
[learn_vxlan_nxos.txt](https://github.com/CiscoTestAutomation/genielibs/files/13648703/learn_vxlan_nxos.txt)

**Comment by kameswararaot** [comment]
Hi @spasekovachev,

Thanks for sharing the details. I am will check and get back to you.

**Comment by sowmyadn010501** [comment]
Hello marehler,
[PR](https://wwwin-github.cisco.com/pyATS/genieparser/pull/3034) has been merged. It will reflect in next release. Hence I am closing this ticket

**Comment by marehler** [comment]
Thank you very much @sowmyadn010501 for fixing this issue.

**Comment by spasekovachev** [comment]
@sowmyadn010501, thanks for fixing the issue. Is the release with the fixed issue already available?

**Comment by sowmyadn010501** [comment]
> @sowmyadn010501, thanks for fixing the issue. Is the release with the fixed issue already available?

As we merged the modification in this version the changes will reflect in next release.
