### ISSUE TITLE
Create verify.py file for new EIGRP verify APIs for EIGRPv4 and EIGRPv6

### ISSUE THREAD

**Issue by cherifimehdi** [CiscoTestAutomation/genielibs#157]
Hello,  I noticed there is no verify.py file and verify apis for ios/iosxe eigrp protocol. So I submitted a pull request #156 containing 02 APIs supporting IPv4 and IPv6  Thank you

**Comment by SohanTirpude** [comment]
Hello @cherifimehdi,

Thanks for taking care of the issue by yourself. Reviewers have provided the reviews on your PR so kindly address those as soon as possible so we can get this PR merged.

Thank you.

**Comment by cherifimehdi** [comment]
Hello @SohanTirpude thank you. I went through all the changes and tested it, it works perfectly.

**Comment by sowmyadn010501** [comment]
Hello @cherifimehdi,
I still saw some unresolved [conversation](https://github.com/CiscoTestAutomation/genielibs/pull/156#discussion_r1514730512), kindly address those as soon as possible so we can get this PR merged.

**Comment by cherifimehdi** [comment]
Hello @sowmyadn010501 thank you. Now I resolved all the conversation with the necessary changes. Thank you

**Comment by sowmyadn010501** [comment]
Thank you once the requested changes are addressed and reviewers reviewed the PR we can get this PR merged.

**Comment by cherifimehdi** [comment]
Hi @SohanTirpude @sowmyadn010501  I addressed all the changes. I would like to ask if it is ok with the changes I made? Thank you

**Comment by sowmyadn010501** [comment]
Hi, Kindly ask again the reviewers to review your pr. If any changes needed they will let you know. thank you

**Comment by sowmyadn010501** [comment]
Hi, Kindly address the commands given by reviewers.

**Comment by cherifimehdi** [comment]
> Hi, Kindly address the commands given by reviewers.

Hi @sowmyadn010501 I addressed all the suggested change this morning. I asked again the reviewers to review the changes I made based on the remarks

**Comment by sowmyadn010501** [comment]
Thank you once reviewers reviewed the PR we can get this PR merged.

**Comment by sowmyadn010501** [comment]
Hi, Since the PR got reviewed and merged. Hence i will be closing this case.

**Comment by cherifimehdi** [comment]
Thank you @sowmyadn010501
