### ISSUE TITLE
Add verify_eigrp_router_id API to verify.py ios/iosxe eigrp protocol (my old contribution) supporting EIGRPv4 and EIGRPv6 for IOS/IOSXE

### ISSUE THREAD

**Issue by cherifimehdi** [CiscoTestAutomation/genielibs#159]
Hello,
I added new API verify_eigrp_router_id to verify.py ios/iosxe eigrp protocol (my old contribution) supporting EIGRPv4 and EIGRPv6 for IOS/IOSXE https://github.com/CiscoTestAutomation/genielibs/pull/158

Thank you for reviewing my contribution

**Comment by cherifimehdi** [comment]
Hi @SohanTirpude  @sowmyadn010501 please can you review and merge my PR since it is an addition to my previous contribution (verifi.py for iosxe eigrp) and I followed same logic based on reviewers from my previous PR @ThomasJRyan and @Lelor.
Thank you

**Comment by Harishv01** [comment]
Hi,

Kindly give me some time.I will check with then and get back

**Comment by cherifimehdi** [comment]
Hi @Harishv01, I'm contacting you about my PR. @lsheikal approved my change. Only @omehrabi remains, I left him a comment. I would like to ask if you can contact him to see if there is anything to add to the changes I made or if everything is okay. THANKS

**Comment by cherifimehdi** [comment]
Hello, thank you for accepting my contribution.

**Comment by SohanTirpude** [comment]
Hello @cherifimehdi,

Since the PR got merged and the fix will be available in the upcoming pyats release, hence I am closing this ticket. If you are facing any other issues, kindly open a new ticket.

Thank you.
