### ISSUE TITLE
Add verify_eigrp_interfaces_timers API to verify.py ios/iosxe eigrp protocol (my previous contribution) supporting EIGRPv4 and EIGRPv6 for IOS/IOSXE 

### ISSUE THREAD

**Issue by cherifimehdi** [CiscoTestAutomation/genielibs#162]
Hello,
I added new API verify_eigrp_interfaces_timers to verify.py ios/iosxe eigrp protocol (my old contribution) supporting EIGRPv4 and EIGRPv6 for IOS/IOSXE https://github.com/CiscoTestAutomation/genielibs/pull/161

Thank you for reviewing my contribution

**Comment by Harishv01** [comment]
Please allow me some time. I will check with the reviewers and expedite the approval process. 

Thank you.

**Comment by cherifimehdi** [comment]
Hi @SohanTirpude @Harishv01 is there any new for my PR? Thank you

**Comment by Harishv01** [comment]
No, Please allow me some time. I am checking with the reviewers

**Comment by cherifimehdi** [comment]
@omehrabi @domachad @SohanTirpude @Harishv01 I think it is better to close this PR and issue relating to it since always tests fail when I try to update my PR according to remarks and since there is no answer why from reviewers. Thanks
