### ISSUE TITLE
Add verify_eigrp_interfaces_timers API to verify.py ios/iosxe eigrp protocol

### ISSUE THREAD

**Issue by cherifimehdi** [CiscoTestAutomation/genielibs#166]
Hello,
I added new API verify_eigrp_interfaces_timers to verify.py ios/iosxe eigrp protocol (my old contribution) supporting EIGRPv4 and EIGRPv6 for IOS/IOSXE https://github.com/CiscoTestAutomation/genielibs/pull/165
Thanks

**Comment by cherifimehdi** [comment]
> Hello @cherifimehdi ,
> 
> Kindly give some time, will check and update you.

Thank you. But I try to contact the reviewers to resolve the problem of tests fail since I closed before a PR just for this and I opened the current PR for this reason

**Comment by Neeraja1bala** [comment]
Hello @cherifimehdi ,

Can you please check the version of genie  is `24.4.3`.

**Comment by cherifimehdi** [comment]
> Hello @cherifimehdi ,
> 
> Can you please check the version of genie is `24.4.3`.

I have genie==23.11

**Comment by Neeraja1bala** [comment]
Can you please update, try to push to PR and let us know.

**Comment by cherifimehdi** [comment]
Hi @Neeraja1bala thank you very much. Finally succeeded after updating pyATS/Genie and downloading a new test files test passed. All that remains is to review the PR. Thank you so much

**Comment by Neeraja1bala** [comment]
Hello @cherifimehdi ,

Thanks for confirmation. Kindly follow up the reviewers to review.

**Comment by cherifimehdi** [comment]
> Hello @cherifimehdi ,
> 
> Thanks for confirmation. Kindly follow up the reviewers to review.

Thank you @Neeraja1bala

**Comment by cherifimehdi** [comment]
Hi @Neeraja1bala could you please contact the reviewers as I made changes and contacted them 02 weeks ago with no response
THANKS

**Comment by cherifimehdi** [comment]
Hi @Neeraja1bala  broken tests when I synced the fork to update the branch! please what is the problem?

**Comment by cherifimehdi** [comment]
Hi @ParimiNeeraja  broken tests when I synced the fork to update the branch! please what is the problem?

**Comment by cherifimehdi** [comment]
Hello @Neeraja1bala  @ParimiNeeraja  still no answer and solution?

**Comment by Neeraja1bala** [comment]
Hello @cherifimehdi ,

Can you give some time, will check and update you.

**Comment by Neeraja1bala** [comment]
Hello @cherifimehdi ,

I am fetching your branch to test in my end, but not able to fetch getting below error,

```
ssh: Could not resolve hostname cherifimehdi: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Kindly help to fetch your branch to test.

**Comment by cherifimehdi** [comment]
> Hello @cherifimehdi ,
> 
> I am fetching your branch to test in my end, but not able to fetch getting below error,
> 
> ```
> ssh: Could not resolve hostname cherifimehdi: Name or service not known
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> Kindly help to fetch your branch to test.

Hi @Neeraja1bala  I think the problem resides in the last update of pyATS. I notice there is a problem in the test of the last update and it seems it was fail.  Here the link to the master repo https://github.com/CiscoTestAutomation/genielibs/tree/master 
There is fail state!

**Comment by cherifimehdi** [comment]
Hi @Neeraja1bala  I found this in Test Unit Tests in Run Tests / build (3.11) , please what is the reason:

ERROR:pyats.aetest.steps.implementation:Failed reason: The following arithmetic statement 3 == 3 and 2 ==1  is False

**Comment by cherifimehdi** [comment]
Hi @Neeraja1bala  @ParimiNeeraja   Now test PASSED after I made update for my branch. I think there was a problem in the prvious version!

**Comment by Neeraja1bala** [comment]
Hello @cherifimehdi ,

Yes, i am checking with them to approve the PR.

**Comment by cherifimehdi** [comment]
> Hello @cherifimehdi ,
> 
> Yes, i am checking with them to approve the PR.

Thank you @Neeraja1bala  but unfortunately there is still no answers from @lsheikal  and @SohanTirpude

**Comment by cherifimehdi** [comment]
Hello, since this PR is merged I will close this issue. Thank you

**Comment by cherifimehdi** [comment]
Thanks
