### ISSUE TITLE
NXOS Model mcast not woriking

### ISSUE THREAD

**Issue by dan-md** [CiscoTestAutomation/genielibs#18]
Hi team,

Want to report an issue on NX9K while trying to learm mcast.

Issue while parsing: <class 'genie.libs.parser.nxos.show_mcast.ShowIpStaticRouteMulticast'>

Traceback (most recent call last):
  File "src/genie/cli/commands/learn.py", line 343, in genie.cli.commands.learn.LearnCommand._retrieve_ops
  File "/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/libs/ops/mcast/nxos/mcast.py", line 117, in learn
    self.make(final_call=True)
  File "/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
    self.maker.make(*args, **kwargs)
  File "src/genie/ops/base/maker.py", line 310, in genie.ops.base.maker.Maker.make
  File "src/genie/ops/base/maker.py", line 414, in genie.ops.base.maker.Maker._call_parser
  File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
  File "src/genie/metaparser/util/schemaengine.py", line 405, in genie.metaparser.util.schemaengine.Schema.validate
genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['vrf', 'default', 'address_family'], ['vrf', 'management', 'address_family']]

-Device output of ""show ip mroute vrf all"
IP Multicast Routing Table for VRF "default"

(*, 232.0.0.0/8), uptime: 7w0d, mrib pim ip
  Incoming interface: Null, RPF nbr: 0.0.0.0
  Outgoing interface list: (count: 0)

(*, 239.0.0.2/32), uptime: 7w0d, mrib nve pim ip
  Incoming interface: Null, RPF nbr: 0.0.0.0
  Outgoing interface list: (count: 1)
    nve1, uptime: 7w0d, nve

(10.150.1.5/32, 239.0.0.2/32), uptime: 7w0d, mrib nve pim ip
  Incoming interface: Null, RPF nbr: 0.0.0.0
  Outgoing interface list: (count: 0)

IP Multicast Routing Table for VRF "ECOM-QUALITY"

Kind regards,
Dan

**Comment by xiaoxinz-cisco** [comment]
Hello @dan-md  ,

Thank you for reporting. We will look into the issue and get back to you.

Just for your information, `pyats learn` is built based on the genieparsers, which is also open-sourced, here it is: https://github.com/CiscoTestAutomation/genieparser

Thanks,
Irene

**Comment by dan-md** [comment]
Hello Irene,

Thank you for your email.
Please correct me if I'm wrong, but based on error, I do not see the issue
is in parser itself:

> genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys:
> [['vrf', 'default', 'address_family'], ['vrf', 'management',
> 'address_family']]


Kind regards,
Dan Gaviuc

**Comment by xiaoxinz-cisco** [comment]
Hello @dan-md ,

Based on the information you provided:

> Issue while parsing: <class 'genie.libs.parser.nxos.show_mcast.ShowIpStaticRouteMulticast'>

It seems current parser **ShowIpStaticRouteMulticast** cannot correctly parse your device output. :https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_mcast.py 

From here

>-Device output of ""show ip mroute vrf all"

I noticed that you shared the output of `show ip mroute vrf all` (**ShowIpMrouteVrfAll**), but not `show ip static-route multicast`.

Could you please execute the `pyats parse` command independently and tell us which parser you are facing issue with, and please share the output of the corresponding show command?

Here is the documentation of the **Genie Command Line**: https://developer.cisco.com/docs/genie-docs/

I'm looking forward to your reply.

Thanks,
Irene

**Comment by dan-md** [comment]
Hello Irene,

Thank you for your email.

Just checked and show ip static-route multicast. is failing.
Device output is empty.
And show ip mroute vrf all -- works fine.

test-NX1#
[2020-04-23 12:40:34,806] +++ test-NX1: executing command 'terminal width
511' +++
terminal width 511
test-NX1#
Traceback (most recent call last):
  File "/srv/netDevOps/networking/network_profile/test_room/testing.py",
line 15, in <module>
    mroute = device.parse('show ip static-route multicast')
  File "src/genie/conf/base/device.py", line 541, in
genie.conf.base.device.Device.parse
  File
"/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/libs/parser/utils/common.py",
line 98, in get_parser
    "'{c}'".format(c=command)) from None
Exception: Could not find parser for 'show ip static-route multicast'

Kind regards,
Dan Gaviuc

**Comment by xiaoxinz-cisco** [comment]
Hi @dan-md ,

I found the issue, we don't have a parser for `show ip static-route multicast` so far, but we have one for `show ip static-route multicast vrf all`

here is its location in the repo: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/show_mcast.py#L450

I tried to get an output of `show ip static-route multicast` from one of my testbed, but didn't find one. Also, I believe you have the device output for this show command. So here are my suggestion steps:

1. execute `device.execute('show ip static-route multicast')` and get the device output
2. compare the output with the existing ones of show ip static-route multicast vrf all unittest: https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/nxos/tests/test_show_mcast.py#L810
3. open a pull request on this repo, add the show command into the existing parser (the first link), and modify the code if necessary. And the Readme outlines the instructions for contributors: https://github.com/CiscoTestAutomation/genieparser/blob/master/README.md
4. I will review your contribution, give you feedback and merge it.

Alright, what do you think? :D

Thanks,
Irene

**Comment by dan-md** [comment]
Hi team,

Thank you for your help.
I checked "show ip static-route multicast vrf all" and  not working as
well.:
*device.parse('show ip static­route multicast vrf all')*

Traceback (most recent call last):
>   File "testing.py", line 16, in <module>
>     mroue = device.parse('show ip static­-route multicast vrf all')
>   File "src/genie/conf/base/device.py", line 541, in
> genie.conf.base.device.Device.parse
>   File
> "/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/libs/parser/utils/common.py",
> line 98, in get_parser
>     "'{c}'".format(c=command)) from None
> Exception: Could not find parser for 'show ip static­-route multicast vrf
> all'


Kind regards,
Dan

**Comment by xiaoxinz-cisco** [comment]
Hi @dan-md ,

Thanks for checking. In your initial post:

> Issue while parsing: <class 'genie.libs.parser.nxos.show_mcast.ShowIpStaticRouteMulticast'>

> Traceback (most recent call last):
> File "src/genie/cli/commands/learn.py", line 343, in genie.cli.commands.learn.LearnCommand._retrieve_ops
> File "/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/libs/ops/mcast/nxos/mcast.py", line 117, in learn
> self.make(final_call=True)
> File "/srv/netDevOps/py3-venv/lib/python3.6/site-packages/genie/ops/base/base.py", line 101, in make
> self.maker.make(*args, **kwargs)
> File "src/genie/ops/base/maker.py", line 310, in genie.ops.base.maker.Maker.make
> File "src/genie/ops/base/maker.py", line 414, in genie.ops.base.maker.Maker._call_parser
> File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse
> File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse
> File "src/genie/metaparser/util/schemaengine.py", line 405, in genie.metaparser.util.schemaengine.Schema.validate
> genie.metaparser.util.exceptions.SchemaMissingKeyError: Missing keys: [['vrf', 'default', 'address_family'], ['vrf', 'management', 'address_family']]

looks like when you were parsing `show ip static-route multicast vrf all`, a `SchemaMissingKeyError` occurs. Can you execute `device.execute('show ip static-route multicast vrf all')` and share the device output with us?

About the `Exception: Could not find parser for ...`, would you mind checking the versions of the packages you have? 

Thanks,
Irene

**Comment by dan-md** [comment]
Hi Team,

I found the issue was in command  which I was using " show ip static-route
multicast vrf all", initially I was copping it from documentation and was
getting the error. Today I typed it and see correct result *"Output is
empty". *
I apologize for this confusion..
Please junk this issue..

After I typed manually the command I'm getting :








*Traceback (most recent call last):  File
"/srv/netDevOps/networking/network_profile/test_room/testing.py", line 16,
in <module>    mroue = device.parse('show ip static-route multicast vrf
all')  File "src/genie/conf/base/device.py", line 548, in
genie.conf.base.device.Device.parse  File
"src/genie/metaparser/_metaparser.py", line 289, in
genie.metaparser._metaparser.MetaParser.parse  File
"src/genie/metaparser/_metaparser.py", line 284, in
genie.metaparser._metaparser.MetaParser.parse  File
"src/genie/metaparser/util/schemaengine.py", line 223, in
genie.metaparser.util.schemaengine.Schema.validategenie.metaparser.util.exceptions.SchemaEmptyParserError:
Parser Output is empty*


Kind regards,
Dan

**Comment by xiaoxinz-cisco** [comment]
for record purpose:
<img width="443" alt="dan" src="https://user-images.githubusercontent.com/60668974/80636663-d29db880-8a2b-11ea-82eb-9931fb1cdaf4.PNG">

**Comment by xiaoxinz-cisco** [comment]
informed on WebEx
