### ISSUE TITLE
NXOS genieRobot: Model route_policy not working

### ISSUE THREAD

**Issue by dan-md** [CiscoTestAutomation/genielibs#19]
Hi Team,

Whne I'm running genie learn route_policy for NXOS it works, but when I'm adding it to robot I'm getting the following error:
`Could not find genie.libs.ops.route_policy.route_policy.Route_Policy for device test-NX1
`
Robot config:
```
Profile the Overlay
   Profile the system for "route_policy" on devices "test_nx" as "./outputs/base_snapshot"
```

=====PyATS version
```
You are currently running pyATS version: 20.2.1
Python: 3.6.9 [64bit]

```
Any ideas what could be the issue?

Kind regards,
Dan

**Comment by xiaoxinz-cisco** [comment]
Hello @dan-md ,

Do you mind send us the robot script that generate this error message?

Thanks,
Irene

**Comment by dan-md** [comment]
Hi Irene,

Thank you for your reply!

here is the robot config:

> # Take initial snapshot of the operational state of the device
> # and save the output to a file
> *** Settings ***
> # Importing test libraries, resource files and variable files.
> Library        ats.robot.pyATSRobot
> Library        genie.libs.robot.GenieRobot
> Library        unicon.robot.UniconRobot
>
>
> *** Variables ***
> # Define the pyATS testbed file to use for this run
> ${testbed}     ../vxlan_testbed.yaml
> *** Test Cases ***
> # Creating test cases from available keywords.
> Connect
>     # Initializes the pyATS/Genie Testbed
>     use genie testbed "${testbed}"
>     # Connect to both device
>     connect to device "test_nx"
> Profile the Overlay
> Profile the system for "route_policy" on devices "test_nx" as
> "./outputs/base_snapshot"


Kind regards,
Dan Gaviuc

**Comment by danielgraziano** [comment]
Hi @dan-md,

I have looked into this issue and found a bug. I will release a beta pkg (v20.5.1b0), please upgrade using "pip install --upgrade --pre genie.libs.robot"

**Comment by dan-md** [comment]
Great !
Thank you Daniel!
