### ISSUE TITLE
Get parse exclude list in Python

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/genielibs#20]
Hello,

I’m carrying out some tests using python scripting to get a similar output to pyats parse. As you know, this provides a parsed file with a list of excludes.

However, I haven’t found a method/ attribute to retrieve those excludes and include them in the python parsed output. I can find the excludes of show commands browsing the methods - or running the equivalent pyats parse command -, yeat I’m looking for a more dynamic method.

Many thanks and regards.

**Comment by jeaubin** [comment]
Hi

You can use this one

https://github.com/CiscoTestAutomation/genieparser/blob/master/src/genie/libs/parser/utils/common.py#L66

Let me know how that works for you

**Comment by naciohr** [comment]
Hello,

That was exaclty what I was looking for.

Thank you very much!
