### ISSUE TITLE
List of show commands run by learn in Python

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/genielibs#21]
Hello,

I’m carrying out some tests using python scripting to get a similar output to **pyats learn**. As you know, this provides a console file with the output of several show commands.

However, I haven't found a method/ attribute that provides what show commands were run. I can get the manual list from the Genie model description or figure out from the arp files, but I'm looking for a more dynamic method.

Many thanks and regards.

**Comment by jeaubin** [comment]
Hi

```
In [26]: x.maker.outputs.keys()
Out[26]: dict_keys([<class 'genie.libs.parser.nxos.show_bgp.ShowBgpProcessVrfAll'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpPeerSession'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpPeerPolicy'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllAllDampeningParameters'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllAllNextHopDatabase'>, <class 'genie.libs.parser.nxos.show_routing.ShowRoutingVrfAll'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllAll'>, <class 'genie.libs.parser.nxos.show_vrf.ShowVrf'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllNeighbors'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllAllSummary'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllNeighborsAdvertisedRoutes'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllNeighborsRoutes'>, <class 'genie.libs.parser.nxos.show_bgp.ShowBgpVrfAllNeighborsReceivedRoutes'>])
```

Will return you a dictionary which contains all the command sent and all the output as the value

**Comment by naciohr** [comment]
Sorry I didn’t have tme to check this out.

I alread knew of this approach but was looking for something more straightforward. I assume this is the best way as the issue was closed.

Thank you very much for your help!
