### ISSUE TITLE
Robot profiling failing

### ISSUE THREAD

**Issue by rowco** [CiscoTestAutomation/genielibs#3]
Hi,

Just running through a very basic test setup, and the Robot integration is failing for me.

```
Profile the devices                                                   | FAIL |
TypeError: pickle() got an unexpected keyword argument 'file'
```

I've just upgraded genielibs to 'develop' and I'm still getting the same issue. 

```
# Importing test libraries, resource files and variable files.
Library        ats.robot.pyATSRobot
Library        genie.libs.robot.GenieRobot


*** Variables ***
# Define the pyATS testbed file to use for this run
${testbed}     ../testbed.yaml 

*** Test Cases ***
# Creating test cases from available keywords.
Connect
    # Initializes the pyATS/Genie Testbed
    use genie testbed "${testbed}"

    # Connect to both device
    connect to device "MEDC1-SWT-2"

Profile the devices
    Profile the system for "interface" on devices "MEDC1-SWT-2" as "./good_snapshot"
```

**Comment by lubnarasheed** [comment]
Hi,

I think you're missing the Unicon import. Could you please add the following import to the top of your file:
Library        unicon.robot.UniconRobot

Regards,
Lubna

**Comment by rowco** [comment]
Thanks for the speedy response.

Unfortunately I'm still seeing the same message with this additional Library line.

**Comment by jeaubin** [comment]
Hi @rowco, 

I'll take a look; you should be able to have good_snapshot as a file. Will do right after this meeting.

**Comment by karmoham** [comment]
Hi Rowco,

I have fixed the issue and pushed it to "dev" branch.

Here are the steps to get the fix;
_under genielibs repo_

```
- git checkout dev
- git pull origin dev
```

Let us know if you have any other question.

Thanks,
Karim

**Comment by rowco** [comment]
Hi.

Yes, that's fixed it. Now to move on to a more complete test. Many thanks.

fyi, I needed to update genie.libs.sdk & genie.libs.ops for it to work.

Rowan

**Comment by jeaubin** [comment]
Glad to hear all is working as expected and letting us know of this issue!
