### ISSUE TITLE
WLC 9800 crypto import certificate

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/genielibs#30]
Hello,

I'm trying to import a certificate to the WLC but it's asking for user interaction always. I'm having 2 approaches to avoid this happening but "human input" is always needed.

**Option 1: using SCP**
```
dev.configure(crypto pki import <cert-filename> pkcs12 scp://<scp_IP>/<cert-filename> password <cert-password>)
```
This asks for:
```
Address or name of remote host [scp_IP]? 
Source username [user]? 
Source filename [path-to-cert]? 
Password:
```
**Option 2: using local file**
After downloading the file in the WLC.
```
dev.configure(crypto pki import <cert-filename> pkcs12 flash:<cert-filename> password <cert-password>)
```
This asks for:
```
Source filename [path-to-cert]? 
```
I've tried different combinations to add "/r" or "/n" to the previous command and with **dev.execute** but I haven't been able to complete the sequence.

In turn, for the WLC with aireos, this commands works and it accepts automatically the final question of starting the download.
```
dev.execute(["transfer download mode sftp", 
                              "transfer download datatype webauthcert", 
                              "transfer download serverip <server>,
                              "transfer download path <path>,
                              "transfer download filename <filename>,
                              "transfer download certpassword <certpassword>,
                              "transfer download username <username>,
                              "transfer download password <password>,
                              "transfer download start"])
```
That processes automaticatlly:
```
This may take some time.
Are you sure you want to start? (y/N) y

SFTP Webauth cert transfer starting.

SFTP receive complete... Installing Certificate.
```

Therefore, I would like to know whether an API for the new WLC 9800 series is going to be released that covers these features or if there is some way to interact with this configuration steps.

Many thanks and regards.

**Comment by ahersi2-cisco** [comment]
Hi naciohr,

I'm currently looking into this issue for you, and will get back to you right away with an update.

Thank you,
Abdurahman

**Comment by ahersi2-cisco** [comment]
Hi naciohr,

I have a question regarding your step option 1. Do you have the neccessary responses for the prompts you showed above. If so there is a way to interact with the configuration steps. Unicon's configure has a reply argument that allows you to pass an additional dialog. In this case it might look like this;

`dialog = Dialog([
    Statement(pattern=r'.*Address or name of remote host [scp_IP]? ',
                        action='sendline('here would be the response)',
                        loop_continue=True,
                        continue_timer=False)`
`cmd = 'your command' `
 `dev.configure(cmd, repy=dialog)`

If you don't need to respond to those prompts you could make action = None, something like the following;
`dialog = Dialog([
    Statement(pattern=r'.*Address or name of remote host [scp_IP]? ',
                        action=None,
                        loop_continue=True,
                        continue_timer=False)`

Let me know if this is something you are looking for.

Thank you,
Abdurahman

**Comment by naciohr** [comment]
Dear Abdurahman,

That's it. I didn't know of that feature. I read the unicon documentation and I was able to implement the statements.

Thank you very much for your help.

Regards.

**Comment by ahersi2-cisco** [comment]
Hi Naciohr,

I'm glad that helped!

Abdurahman
