### ISSUE TITLE
timeout when run parse/learn

### ISSUE THREAD

**Issue by zkzqzk** [CiscoTestAutomation/genielibs#32]
Hi, 

I use parse/learn function inside python script  , when I run it against some heavily used devices,  the parse/learn timed out at 60 seconds,  How can we adjust the timeout value? 

I found that how to adjust timeout it in Genie cli using --timeout argument,  but I couldn't find out how to do it in python function like  "output = device.parse('show interface detail')"

Your help will be appreciated

**Comment by KamyarZiabari** [comment]
Hi @zkzqzk,

You can set the execution timeout for any device in your python script like below.

`device.execute.timeout = 300`

**Comment by zkzqzk** [comment]
Thanks, also managed to define  EXEC_TIMEOUT in testbed yaml file to solve the problem.
