### ISSUE TITLE
Genie model for standard access-lists

### ISSUE THREAD

**Issue by naciohr** [CiscoTestAutomation/genielibs#33]
Hello,

I would like to know if there is some workaround to apply the ACL model based instructions for standard access-lists. I mean, some stepped process rather than a raw `dev.configure("ip access-list standard <name>")`.

Many thanks and regards.

**Comment by ahersi2-cisco** [comment]
Hi,

Including @Thai Nguyen (thaing)<mailto:thaing@cisco.com> for support.

Thank you,
Abdurahman
________________________________

**Comment by thaixuann** [comment]
Hello @naciohr ,
Thanks for reaching out to us.
Please take a look at the User Guide, the build_config for more info.

http://wwwin-pyats.cisco.com/cisco-shared/genie/latest/userguide/index.html

-- Thai.

**Comment by naciohr** [comment]
Dear Thai,

Many thanks for your reply. I'm afraid thr link is not working for me. May you double check it's correct, please?

Best regards.

**Comment by thaixuann** [comment]
Hi @naciohr ,
Sorry about that. Please try this link: https://developer.cisco.com/docs/genie-docs/

Thanks,
--Thai.

**Comment by jeaubin** [comment]
More specifically - https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/#/models/acl 

Thanks,
