### ISSUE TITLE
Learn STP SchemaMissingKeyError:

### ISSUE THREAD

**Issue by wilbeacham85** [CiscoTestAutomation/genielibs#38]
When Using the Learn STP Feature i get a SchemaMissingKeyError. This is on a 2960X running IOS. 

Please See Attached Robot log and traceback below

[log.zip](https://github.com/CiscoTestAutomation/genielibs/files/5819255/log.zip)

`

  | SchemaMissingKeyError: Missing keys: [['rapid_pvst', 'vlans', 1, 'interfaces'], ['rapid_pvst', 'vlans', 2, 'interfaces'], ['rapid_pvst', 'vlans', 11, 'interfaces'], ['rapid_pvst', 'vlans', 12, 'interfaces'], ['rapid_pvst', 'vlans', 20, 'interfaces'], ['rapid_pvst', 'vlans', 99, 'interfaces'], ['rapid_pvst', 'vlans', 701, 'interfaces'], ['rapid_pvst', 'vlans', 900, 'interfaces'], ['rapid_pvst', 'vlans', 990, 'interfaces']]
-- | --

`

`

  | Traceback (most recent call last):   File "/venv/lib/python3.7/site-packages/genie/libs/robot/GenieRobot.py", line 162, in genie_ops_on_device     device=device)   File "/venv/lib/python3.7/site-packages/genie/libs/robot/GenieRobot.py", line 243, in genie_ops_on_device_alias_context     ops.learn()   File "/venv/lib/python3.7/site-packages/genie/libs/ops/stp/iosxe/stp.py", line 128, in learn     self.make(final_call=True)   File "/venv/lib/python3.7/site-packages/genie/ops/base/base.py", line 101, in make     self.maker.make(*args, **kwargs)   File "src/genie/ops/base/maker.py", line 312, in genie.ops.base.maker.Maker.make   File "src/genie/ops/base/maker.py", line 418, in genie.ops.base.maker.Maker._call_parser   File "src/genie/metaparser/_metaparser.py", line 302, in genie.metaparser._metaparser.MetaParser.parse   File "src/genie/metaparser/_metaparser.py", line 284, in genie.metaparser._metaparser.MetaParser.parse   File "src/genie/metaparser/util/schemaengine.py", line 405, in genie.metaparser.util.schemaengine.Schema.validate
-- | --

`

**Comment by badalsoyantar** [comment]
Hi @wilbeacham85. Fix is merged! Will ping you here once it is released!

**Comment by tahigash** [comment]
sorry for delayed update. The fix is already in 21.2 release. If see the same issue with latest, please reopen.
