### ISSUE TITLE
static routing configuration not applying without device_attr

### ISSUE THREAD

**Issue by rohit04saluja** [CiscoTestAutomation/genielibs#39]
The following code should apply ```ip route 10.2.1.0/24 192.168.0.1``` config to all devices in ```sr.devices```

```
sr = StaticRouting()
sr.af = 'ipv4'
sr.route = '10.2.1.0/24'
sr.nexthop = '192.168.0.1'
device1.add_feature(sr)
device2.add_feature(sr)
sr.build_config()
```

The above config results in an empty configuration when build_config() is called

The configuration is not generated without ```device_attr```.

**Comment by ahersi2-cisco** [comment]
Hi,

Just to clarify, are you saying configuration is not being applied when you don't use 'device_attr'? So applying configuration worked when you did use 'device_attr'? 'device_attr' is always the first level of a conf object. Please let me know if I understood your question correctly.

Thank you,
Abdurahman

**Comment by rohit04saluja** [comment]
@ahersi2-cisco your understanding is correct.

I am trying to understand from a usability perspective. For a simple configuration like the one I have mentioned, I need to write the following apart from the code I have mentioned already

```sr.device_attr[self.dut].vrf_attr[None].address_family_attr[sr.af].route_attr[sr.route].next_hop_attr[sr.nexthop]```

Can't we assume some default values? Like _default_ vrf etc?

**Comment by ahersi2-cisco** [comment]
I believe I understand what you are referring to. There are some some assumptions we can make where the default values could be 'default'. For example, vrf_attr['default'], or vrf_attr[None] like you showed above. Is this what you are referring to?

**Comment by rohit04saluja** [comment]
Yes. Exactly.

**Comment by ThomasJRyan** [comment]
Hello @rohit04saluja,

Something like this is doable, though as it doesn't appear to be feature breaking it will have to go on my backlog and I'm not sure when it will get done. You are welcome to try implementing it yourself and creating a PR if you'd like, otherwise it will be a while.

**Comment by rohit04saluja** [comment]
Thank you for the confirmation. I will try my hand at it if I get some bandwidth
