### ISSUE TITLE
Interface learn methods include 'show interface switchport' commands only when running against NXOS devices.

### ISSUE THREAD

**Issue by andyburridge** [CiscoTestAutomation/genielibs#43]
When l call interface.learn('interface') on both an IOS and IOS-XE device, it runs the following:

executing command 'show interfaces' +++
executing command 'show interfaces accounting' +++
executing command 'show ip interface' +++
executing command 'show ipv6 interface' +++

When I call the same function on a NXOS device, it runs the above commands, but also runs 'show interface switchport'.

This is reflected in the codebase for interface:

https://github.com/CiscoTestAutomation/genielibs/tree/master/pkgs/ops-pkg/src/genie/libs/ops/interface

Is there a technical or policy reason that it isn't included for IOS/IOS-XE devices, or would it be possible to add this parser module?  

Thanks,

Andy

**Comment by KamyarZiabari** [comment]
Hi @andyburridge 
We are following specific yang models https://pubhub.devnetcloud.com/media/genie-feature-browser/docs/_models/interface.pdf to select the values and hence selecting the parser. We can add the parser to the module if and only if it fits this models.

Let me know if you need anything else.
Regards,
Kamyar

**Comment by andyburridge** [comment]
Hey Kamyar, appreciate the explanation - now I understand.

Thanks,

Andy
