### ISSUE TITLE
Using trunk_add_vlans on the Interface model

### ISSUE THREAD

**Issue by Kircheneer** [CiscoTestAutomation/genielibs#44]
How is the trunk_add_vlans field on the Interface model used?

I tried with the below code, yet all it does is output the following:

```
Traceback (most recent call last):
  File "ats/main.py", line 23, in <module>
    raise Exception(interface.build_config(apply=False))
Exception: interface Ethernet1/48
 exit
```

I would have expected 

```
Traceback (most recent call last):
  File "ats/main.py", line 23, in <module>
    raise Exception(interface.build_config(apply=False))
Exception: interface Ethernet1/48
  switchport trunk add vlan 2222 
exit
```

```
from dotenv import load_dotenv
from genie.testbed import load
from genie.libs.conf.vlan import Vlan
from genie.libs.conf.interface import Interface

load_dotenv()
tb = load('testbed.yml')

# Connect to all devices
tb.connect()

VLAN_ID = '2222'
vlan = Vlan(vlan_id=VLAN_ID, name='Test')

config = {}

for name, device in tb.devices.items():
    device.add_feature(vlan)
    interface = Interface(device=device, name='Ethernet1/48')
    interface.trunk_add_vlans = VLAN_ID
    raise Exception(interface.build_config(apply=False))
    config[name] = device.build_config(apply=False)

for name, lines in config.items():
    print(f'*** Proposed config changes for {name} ***')
    print(lines)
```

Thanks.

**Comment by Kircheneer** [comment]
I have found the solution. You need to first set
```
interface.switchport_enable = True
interface.switchport_mode = 'trunk'
```
That leads me to another question - is it possible to import present configuration on the device into an Interface object?

**Comment by tahigash** [comment]
> I have found the solution. You need to first set
> 
> ```
> interface.switchport_enable = True
> interface.switchport_mode = 'trunk'
> ```

Yes. As you found, you need those. As FYI, unittest files will be good reference for how to use Conf.
https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/src/genie/libs/conf/interface/nxos/tests/test_interface.py#L104

> That leads me to another question - is it possible to import present configuration on the device into an Interface object?

Unfortunately, we don't have that functionality.

**Comment by Kircheneer** [comment]
Thank you for elaborating.
