### ISSUE TITLE
Vlan Conf object produces logging configuration

### ISSUE THREAD

**Issue by Kircheneer** [CiscoTestAutomation/genielibs#45]
When using genie.conf with the Vlan object
```
from genie.libs.conf.vlan import Vlan
vlan = Vlan(vlan_id=10, name="test")
vlan.build_config(apply=False)
```

The generated config contains configuration to
- Configure the VLAN and
- Configure `logging logfile messages 5`

I don't think the latter is desired. Dave Wapstra told me in the pyATS community on Webex Teams that this is due to the following line: https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/src/genie/libs/conf/device/nxos/device.py#L61

Looking at the config it appears that this happens for all NXOS Device objects. Is this intended behavior?

**Comment by tahigash** [comment]
I didn't see the `logging logfile messages 5` via `vlan.build_config()` on my test. but the line what @dwapstra shared is not expected. we will remove in 20.2 which will be released at end of Feb).
```
In [4]: vlan.build_config()

2021-02-13 11:38:53,311: %UNICON-INFO: +++ R3_nx with alias 'cli': configure +++
config term
Enter configuration commands, one per line. End with CNTL/Z.
R3_nx(config)# vlan 10
R3_nx(config-vlan)#  name test
R3_nx(config-vlan)#  exit
R3_nx(config)# end
R3_nx#

**Comment by tahigash** [comment]
We will remove below line in 21.2 release.
https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/conf-pkg/src/genie/libs/conf/device/nxos/device.py#L61

So, you will not see `logging logfile messages` by build_config(). closing this issue. please feel free to update or reopen if any queries.
