### ISSUE TITLE
Documentation Issue: default_interface [XE] docstring is wrong

### ISSUE THREAD

**Issue by clay584** [CiscoTestAutomation/genielibs#46]
https://github.com/CiscoTestAutomation/genielibs/blob/master/pkgs/sdk-pkg/src/genie/libs/sdk/apis/iosxe/interface/configure.py#L957

This has the wrong docstring for what the API actually does.

**Comment by ThomasJRyan** [comment]
Thank you for letting us know. We'll take a look into fixing that up

**Comment by ThomasJRyan** [comment]
We've fixed this internally. The changes will be reflected on the next release
