### ISSUE TITLE
Genie Error when trying to install through git repo make develop 

### ISSUE THREAD

**Issue by hayroute** [CiscoTestAutomation/genielibs#5]
Hi, 
First i tried using pip install and later tried cloning git repo. Followed link https://developer.cisco.com/codeexchange/github/repo/CiscoTestAutomation/genielibs

however when issuing make develop, getting following error( attached file for review)
--------------------------------------------------------------------
Installing development dependencies

Creating /usr/lib/python2.7/site-packages/genie.libs.robot.egg-link (link to src)
genie.libs.robot 19.0.0 is already the active version in easy-install.pth

Installed /root/genielibs/pkgs/robot-pkg/src
running develop
Traceback (most recent call last):
  File "setup.py", line 192, in <module>
    zip_safe = False,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 79, in run
    super().run(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)
### make: *** [develop] Error 1
[genie-error.txt](https://github.com/CiscoTestAutomation/genielibs/files/3048097/genie-error.txt)

**Comment by siming85** [comment]
pyATS & Genie supports Python 3.4+ (3.5, 3.6, 3.7).

It appears you are trying to install into Python 2.7, which is definitely not in the support range.

since you are using system linux, try installing:

```
# debian/ubuntu
sudo apt-get install python3 python3-venv python3-pip

# cento/rhel
sudo yum install python3
```

**Comment by hayroute** [comment]
Thanks for prompt response, i am using Centos and python3 is installed already, is this something to do with environment path/variables ? 

[root@localhost genielibs]# python3 --version
Python 3.4.9

**Comment by siming85** [comment]
the make file comes with assumption that `python` refers to python3 and not python.

if you are using the system python distro, typically `python` points to python2 and not python3.

the good approach is to create a virtual environment using python3.

```
mkdir ~/pyats
cd ~/pyats
python3 -m venv .

source bin/activate

# now install what packages make develop etc
```

**Comment by hayroute** [comment]
Thank you! that make perfect sense, what about impact on gcc or other libs ? I will test it out and will update

**Comment by siming85** [comment]
it will not impact other libs. all virtual environment does is change PYTHONPATH and PATH to use files from this folder.

Let us know how it works

**Comment by hayroute** [comment]
awsome, it helped. thank you.

**Comment by siming85** [comment]
glad it helped!
