### ISSUE TITLE
ios clean fails due to ImageHandler

### ISSUE THREAD

**Issue by wilbeacham85** [CiscoTestAutomation/genielibs#58]
When i try and do a clean on a IOS device I get the following error

`LookupError: No such attribute in abstraction package 'genie.libs.clean': 'genie.libs.clean.stages.image_handler.ImageHandler'`
Please see attached Kleenex log file
[Kleenex.log](https://github.com/CiscoTestAutomation/genielibs/files/6631765/Kleenex.log)

**Comment by tahigash** [comment]
@wilbeacham85 Please check below doc.
https://pubhub.devnetcloud.com/media/genie-docs/docs/clean/supported_os_platform.html#supported-os-platforms

`ios` is not supported. `ios` is similar with `iosxe`, so code might be leveraged. we have devloper guide. if you need, please consider contributing clean for `ios`.
https://pubhub.devnetcloud.com/media/genie-docs/docs/clean/developer_guide/index.html#developer-guide

**Comment by tahigash** [comment]
@wilbeacham85 thanks for opening PR https://github.com/CiscoTestAutomation/genielibs/pull/62. we can track and discuss on PR if any. so closing this issue.
