### ISSUE TITLE
Missing parser keys

### ISSUE THREAD

**Issue by purplecomputer** [CiscoTestAutomation/genielibs#87]
Hello, 

running into an issue when running this parser on IOS devices.

this is my code in my flask container

```
interfaceSwitchObj = self.device.parse(f"show interfaces {interface}/{num} switchport")
```

error in question

```
Missing keys: [['Port-channel17', 'switchport_enable'], ['Port-channel17', 'switchport_mode']]"
```

so far, i've really only encourted this on my IOS devices, NXOS seem to be working fine.

**Comment by GerriorL** [comment]
Hi Angelo,

Would it be possible for you to provide some more information such as your device's raw output? This will allow us to troubleshoot your issue better as Missing Key errors typically happen when something in the raw output isn't being parsed correctly.

**Comment by purplecomputer** [comment]
Hey Liam,

Sure thing! here is the raw CLI output for the same command. Let me know if thats _not_ what you meant :)

```
#show int gigabitEthernet 1/1 switchport 
Name: Gi1/1
Switchport: Enabled
Administrative Mode: static access
Operational Mode: static access (member of bundle Po17)
Administrative Trunking Encapsulation: negotiate
Operational Trunking Encapsulation: native
Operational Dot1q Ethertype:  0x8100
Negotiation of Trunking: Off
Access Mode VLAN: 607 (<SANITIZED>)
Trunking Native Mode VLAN: 1 (default)
Administrative Native VLAN tagging: enabled
Operational Native VLAN tagging: disabled
Voice VLAN: none
Administrative private-vlan host-association: none 
Administrative private-vlan mapping: none 
Operational private-vlan: none
Trunking VLANs Enabled: ALL
Pruning VLANs Enabled: 2-1001
Capture Mode Disabled
Capture VLANs Allowed: ALL

Unknown unicast blocked: disabled
Unknown multicast blocked: disabled
```

I removed some client information just to be on the safe side. This is on an IOS device, I know its very old. We are in the process of using your library to migrate to new systems etc.

```
cisco WS-C6506 (R7000) processor (revision 3.0) with 458720K/65536K bytes of memory.
Processor board ID TSC070200AM
SR71000 CPU at 600Mhz, Implementation 0x504, Rev 1.2, 512KB L2 Cache
Last reset from s/w reset
267 Virtual Ethernet interfaces
82 Gigabit Ethernet interfaces
4 Ten Gigabit Ethernet interfaces
1917K bytes of non-volatile configuration memory.

65536K bytes of Flash internal SIMM (Sector size 512K).
Configuration register is 0x2102
```

Hope this information helps/

**Comment by GerriorL** [comment]
So as far as I can tell, the parser is creating the structure for the Port-channel17 interface sub-dict, but it's missing some of the information we don't consider optional. 

I suspect that it may be to the specific command you're running - it could be that it sees that port channel 17 exists for G1/1 but it never encounters the actual show interfaces entry for it. Could you try running `interfaceSwitchObj = self.device.parse(f"show interfaces {interface} switchport")` to see if it parses without error?

**Comment by purplecomputer** [comment]
I tried making changes, and what I receive now is this when testing with postman

```
"could not pull requested information - Invalid command has been executed"
```

I cant seem to find any more meaning information

**Comment by GerriorL** [comment]
Sorry for the late reply - There was an issue in the logic for parsing single interfaces, which has been resolved. It will be in the next version release

**Comment by purplecomputer** [comment]
Thank you for updating me!
