### ISSUE TITLE
Profile the system config and compare fails because of timestamp

### ISSUE THREAD

**Issue by toebivankenoebi** [CiscoTestAutomation/genielibs#99]
When running `profile the system for "config"` before and after some configuration changes and then comparing the two outputs with the `compare profile` keyword the test result fails also in case of NO changes applied because of timestamps in the `show run` command. 

First run it fails as expected showing the normal diff.
Second run it fails again only showing the timestamp in the diff.

Testcases:
```
Profile the system config before config
    Profile the system for "config" on devices "<my_device>" as "./config_before_snapshot"

<snip>
# here are some configuration changes

Profile the system config after config
    Profile the system for "config" on devices "<my_device>" as "./config_after_snapshot"

Compare config snapshot
    Compare profile "./config_before_snapshot" with "./config_after_snapshot" on devices "<my_device>"
```

Result on the second run when no config changes were applied:
```
KEYWORD genie.libs.robot.GenieRobot . Compare profile "./config_before_snapshot" with "./config_after_snapshot" on devices "<my_device>"
Compare system profiles taken as snapshots during the run

Start / End / Elapsed:	20220322 08:41:51.180 / 20220322 08:41:51.249 / 00:00:00.069
08:41:51.249	FAIL	
**********
Comparison between ./config_before_snapshot and ./config_after_snapshot is different for feature 'config' for device:

'<my_device>'
+Tue Mar 22 08:41:35.183 MET
-Tue Mar 22 08:41:26.209 MET
```

System:
- cisco NCS-5500
- Cisco IOS XR Software, Version 6.6.3

**Comment by tahigash** [comment]
sorry for delayed response. as you see, with XR, we need to exclude the pattern like `Tue Mar 22 08:41:35.183 MET`. So I will add that pattern as exclude list and the fix will be available in 22.7 (end of this month release)

**Comment by tahigash** [comment]
sorry, it will be in 22.8 release (end of august). but fix is ready. let me know if you need beta package for your test. closing issue.

**Comment by toebivankenoebi** [comment]
thanks Takashi for your work. Will eventually test it once we upgraded to that version, no need to test before.
